var h;h||=typeof Module != 'undefined' ? Module : {};var aa="object"==typeof window,ba="undefined"!=typeof WorkerGlobalScope,ca="object"==typeof process&&process.versions?.node&&"renderer"!=process.type,da=[],fa="./this.program",ha=(a,b)=>{throw b;},ia="undefined"!=typeof document?document.currentScript?.src:void 0;"undefined"!=typeof __filename?ia=__filename:ba&&(ia=self.location.href);var ja="",ka,la;
if(ca){var fs=require("fs");ja=__dirname+"/";la=a=>{a=ma(a)?new URL(a):a;return fs.readFileSync(a)};ka=async a=>{a=ma(a)?new URL(a):a;return fs.readFileSync(a,void 0)};1<process.argv.length&&(fa=process.argv[1].replace(/\\/g,"/"));da=process.argv.slice(2);"undefined"!=typeof module&&(module.exports=h);ha=(a,b)=>{process.exitCode=a;throw b;}}else if(aa||ba){try{ja=(new URL(".",ia)).href}catch{}ba&&(la=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});
ka=async a=>{if(ma(a))return new Promise((c,d)=>{var e=new XMLHttpRequest;e.open("GET",a,!0);e.responseType="arraybuffer";e.onload=()=>{200==e.status||0==e.status&&e.response?c(e.response):d(e.status)};e.onerror=d;e.send(null)});var b=await fetch(a,{credentials:"same-origin"});if(b.ok)return b.arrayBuffer();throw Error(b.status+" : "+b.url);}}var na=console.log.bind(console),l=console.error.bind(console),oa,pa=!1,qa,ma=a=>a.startsWith("file://"),ra,m,p,sa,ta,t,u,v,y,z;
function ua(){var a=ra.buffer;m=new Int8Array(a);sa=new Int16Array(a);p=new Uint8Array(a);ta=new Uint16Array(a);t=new Int32Array(a);u=new Uint32Array(a);v=new Float32Array(a);y=new Float64Array(a);z=new BigInt64Array(a);new BigUint64Array(a)}var va=0,wa=null;function xa(){va++;h.monitorRunDependencies?.(va)}function ya(){va--;h.monitorRunDependencies?.(va);if(0==va&&wa){var a=wa;wa=null;a()}}
function za(a){h.onAbort?.(a);a="Aborted("+a+")";l(a);pa=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var Aa;async function Ba(a){if(!oa)try{var b=await ka(a);return new Uint8Array(b)}catch{}if(a==Aa&&oa)a=new Uint8Array(oa);else if(la)a=la(a);else throw"both async and sync fetching of the wasm failed";return a}
async function Ca(a,b){try{var c=await Ba(a);return await WebAssembly.instantiate(c,b)}catch(d){l(`failed to asynchronously prepare wasm: ${d}`),za(d)}}async function Da(a){var b=Aa;if(!oa&&"function"==typeof WebAssembly.instantiateStreaming&&!ma(b)&&!ca)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){l(`wasm streaming compile failed: ${d}`),l("falling back to ArrayBuffer instantiation")}return Ca(b,a)}
class Ea{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var Fa=a=>{for(;0<a.length;)a.shift()(h)},Ga=[],Ha=[],Ia=()=>{var a=h.preRun.shift();Ha.push(a)},Ja=!0,A=()=>{var a=t[+Ka>>2];Ka+=4;return a},La=(a,b)=>{for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a},Ma=a=>{var b="/"===a.charAt(0),c="/"===a.slice(-1);(a=La(a.split("/").filter(d=>!!d),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a},Na=a=>{var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);
a=b[0];b=b[1];if(!a&&!b)return".";b&&=b.slice(0,-1);return a+b},Oa=()=>{if(ca){var a=require("crypto");return b=>a.randomFillSync(b)}return b=>crypto.getRandomValues(b)},Pa=a=>{(Pa=Oa())(a)},Qa=(...a)=>{for(var b="",c=!1,d=a.length-1;-1<=d&&!c;d--){c=0<=d?a[d]:"/";if("string"!=typeof c)throw new TypeError("Arguments to path.resolve must be strings");if(!c)return"";b=c+"/"+b;c="/"===c.charAt(0)}b=La(b.split("/").filter(e=>!!e),!c).join("/");return(c?"/":"")+b||"."},Ra=new TextDecoder,Sa=a=>{for(var b=
0;a[b]&&!(NaN<=b);)++b;return Ra.decode(a.buffer?a.subarray(0,b):new Uint8Array(a.slice(0,b)))},Ta=[],Ua=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},C=(a,b,c,d)=>{if(!(0<d))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var g=a.codePointAt(f);if(127>=g){if(c>=d)break;b[c++]=g}else if(2047>=g){if(c+1>=d)break;b[c++]=192|g>>6;b[c++]=128|g&63}else if(65535>=g){if(c+2>=d)break;b[c++]=224|g>>12;b[c++]=128|g>>6&63;
b[c++]=128|g&63}else{if(c+3>=d)break;b[c++]=240|g>>18;b[c++]=128|g>>12&63;b[c++]=128|g>>6&63;b[c++]=128|g&63;f++}}b[c]=0;return c-e},Va=a=>{var b=Array(Ua(a)+1);a=C(a,b,0,b.length);b.length=a;return b},Wa=[];function Xa(a,b){Wa[a]={input:[],output:[],Ec:b};Ya(a,Za)}
var Za={open(a){var b=Wa[a.node.rdev];if(!b)throw new D(43);a.tty=b;a.seekable=!1},close(a){a.tty.Ec.fsync(a.tty)},fsync(a){a.tty.Ec.fsync(a.tty)},read(a,b,c,d){if(!a.tty||!a.tty.Ec.qd)throw new D(60);for(var e=0,f=0;f<d;f++){try{var g=a.tty.Ec.qd(a.tty)}catch(k){throw new D(29);}if(void 0===g&&0===e)throw new D(6);if(null===g||void 0===g)break;e++;b[c+f]=g}e&&(a.node.atime=Date.now());return e},write(a,b,c,d){if(!a.tty||!a.tty.Ec.ad)throw new D(60);try{for(var e=0;e<d;e++)a.tty.Ec.ad(a.tty,b[c+e])}catch(f){throw new D(29);
}d&&(a.node.mtime=a.node.ctime=Date.now());return e}},$a={qd(){a:{if(!Ta.length){var a=null;if(ca){var b=Buffer.alloc(256),c=0,d=process.stdin.fd;try{c=fs.readSync(d,b,0,256)}catch(e){if(e.toString().includes("EOF"))c=0;else throw e;}0<c&&(a=b.slice(0,c).toString("utf-8"))}else"undefined"!=typeof window&&"function"==typeof window.prompt&&(a=window.prompt("Input: "),null!==a&&(a+="\n"));if(!a){a=null;break a}Ta=Va(a)}a=Ta.shift()}return a},ad(a,b){null===b||10===b?(na(Sa(a.output)),a.output=[]):0!=
b&&a.output.push(b)},fsync(a){0<a.output?.length&&(na(Sa(a.output)),a.output=[])},Od(){return{ce:25856,ee:5,be:191,de:35387,ae:[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]}},Pd(){return 0},Qd(){return[24,80]}},ab={ad(a,b){null===b||10===b?(l(Sa(a.output)),a.output=[]):0!=b&&a.output.push(b)},fsync(a){0<a.output?.length&&(l(Sa(a.output)),a.output=[])}},E={yc:null,Dc(){return E.createNode(null,"/",16895,0)},createNode(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new D(63);
E.yc||(E.yc={dir:{node:{wc:E.qc.wc,zc:E.qc.zc,lookup:E.qc.lookup,Qc:E.qc.Qc,rename:E.qc.rename,unlink:E.qc.unlink,rmdir:E.qc.rmdir,readdir:E.qc.readdir,symlink:E.qc.symlink},stream:{xc:E.pc.xc}},file:{node:{wc:E.qc.wc,zc:E.qc.zc},stream:{xc:E.pc.xc,read:E.pc.read,write:E.pc.write,Zc:E.pc.Zc,vd:E.pc.vd}},link:{node:{wc:E.qc.wc,zc:E.qc.zc,readlink:E.qc.readlink},stream:{}},kd:{node:{wc:E.qc.wc,zc:E.qc.zc},stream:bb}});c=cb(a,b,c,d);G(c.mode)?(c.qc=E.yc.dir.node,c.pc=E.yc.dir.stream,c.oc={}):32768===
(c.mode&61440)?(c.qc=E.yc.file.node,c.pc=E.yc.file.stream,c.rc=0,c.oc=null):40960===(c.mode&61440)?(c.qc=E.yc.link.node,c.pc=E.yc.link.stream):8192===(c.mode&61440)&&(c.qc=E.yc.kd.node,c.pc=E.yc.kd.stream);c.atime=c.mtime=c.ctime=Date.now();a&&(a.oc[b]=c,a.atime=a.mtime=a.ctime=c.atime);return c},se(a){return a.oc?a.oc.subarray?a.oc.subarray(0,a.rc):new Uint8Array(a.oc):new Uint8Array(0)},qc:{wc(a){var b={};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=
a.rdev;G(a.mode)?b.size=4096:32768===(a.mode&61440)?b.size=a.rc:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.atime=new Date(a.atime);b.mtime=new Date(a.mtime);b.ctime=new Date(a.ctime);b.blksize=4096;b.blocks=Math.ceil(b.size/b.blksize);return b},zc(a,b){for(var c of["mode","atime","mtime","ctime"])null!=b[c]&&(a[c]=b[c]);void 0!==b.size&&(b=b.size,a.rc!=b&&(0==b?(a.oc=null,a.rc=0):(c=a.oc,a.oc=new Uint8Array(b),c&&a.oc.set(c.subarray(0,Math.min(b,a.rc))),a.rc=b)))},lookup(){throw E.nd;
},Qc(a,b,c,d){return E.createNode(a,b,c,d)},rename(a,b,c){try{var d=db(b,c)}catch(f){}if(d){if(G(a.mode))for(var e in d.oc)throw new D(55);eb(d)}delete a.parent.oc[a.name];b.oc[c]=a;a.name=c;b.ctime=b.mtime=a.parent.ctime=a.parent.mtime=Date.now()},unlink(a,b){delete a.oc[b];a.ctime=a.mtime=Date.now()},rmdir(a,b){var c=db(a,b),d;for(d in c.oc)throw new D(55);delete a.oc[b];a.ctime=a.mtime=Date.now()},readdir(a){return[".","..",...Object.keys(a.oc)]},symlink(a,b,c){a=E.createNode(a,b,41471,0);a.link=
c;return a},readlink(a){if(40960!==(a.mode&61440))throw new D(28);return a.link}},pc:{read(a,b,c,d,e){var f=a.node.oc;if(e>=a.node.rc)return 0;a=Math.min(a.node.rc-e,d);if(8<a&&f.subarray)b.set(f.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=f[e+d];return a},write(a,b,c,d,e,f){b.buffer===m.buffer&&(f=!1);if(!d)return 0;a=a.node;a.mtime=a.ctime=Date.now();if(b.subarray&&(!a.oc||a.oc.subarray)){if(f)return a.oc=b.subarray(c,c+d),a.rc=d;if(0===a.rc&&0===e)return a.oc=b.slice(c,c+d),a.rc=d;if(e+d<=a.rc)return a.oc.set(b.subarray(c,
c+d),e),d}f=e+d;var g=a.oc?a.oc.length:0;g>=f||(f=Math.max(f,g*(1048576>g?2:1.125)>>>0),0!=g&&(f=Math.max(f,256)),g=a.oc,a.oc=new Uint8Array(f),0<a.rc&&a.oc.set(g.subarray(0,a.rc),0));if(a.oc.subarray&&b.subarray)a.oc.set(b.subarray(c,c+d),e);else for(f=0;f<d;f++)a.oc[e+f]=b[c+f];a.rc=Math.max(a.rc,e+d);return d},xc(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.rc);if(0>b)throw new D(28);return b},Zc(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new D(43);a=a.node.oc;
if(e&2||!a||a.buffer!==m.buffer){d=!0;za();e=void 0;if(!e)throw new D(48);if(a){if(0<c||c+b<a.length)a.subarray?a=a.subarray(c,c+b):a=Array.prototype.slice.call(a,c,c+b);m.set(a,e)}}else d=!1,e=a.byteOffset;return{Be:e,Yd:d}},vd(a,b,c,d){E.pc.write(a,b,0,d,c,!1);return 0}}},fb=async a=>{a=await ka(a);return new Uint8Array(a)},gb=[],hb=(a,b,c,d)=>{"undefined"!=typeof Browser&&Browser.te();var e=!1;gb.forEach(f=>{!e&&f.canHandle(b)&&(f.handle(a,b,c,d),e=!0)});return e},ib=(a,b)=>{var c=0;a&&(c|=365);
b&&(c|=146);return c},jb=null,kb={},lb=[],mb=1,nb=null,ob=!1,pb=!0,qb={},D=class{name="ErrnoError";constructor(a){this.tc=a}},rb=class{sc={};node=null;get flags(){return this.sc.flags}set flags(a){this.sc.flags=a}get position(){return this.sc.position}set position(a){this.sc.position=a}},sb=class{qc={};pc={};Lc=null;constructor(a,b,c,d){a||=this;this.parent=a;this.Dc=a.Dc;this.id=mb++;this.name=b;this.mode=c;this.rdev=d;this.atime=this.mtime=this.ctime=Date.now()}get read(){return 365===(this.mode&
365)}set read(a){a?this.mode|=365:this.mode&=-366}get write(){return 146===(this.mode&146)}set write(a){a?this.mode|=146:this.mode&=-147}get Sd(){return G(this.mode)}get Rd(){return 8192===(this.mode&61440)}};
function tb(a,b={}){if(!a)throw new D(44);b.Vc??(b.Vc=!0);"/"===a.charAt(0)||(a="//"+a);var c=0;a:for(;40>c;c++){a=a.split("/").filter(k=>!!k);for(var d=jb,e="/",f=0;f<a.length;f++){var g=f===a.length-1;if(g&&b.parent)break;if("."!==a[f])if(".."===a[f])if(e=Na(e),d===d.parent){a=e+"/"+a.slice(f+1).join("/");continue a}else d=d.parent;else{e=Ma(e+"/"+a[f]);try{d=db(d,a[f])}catch(k){if(44===k?.tc&&g&&b.Ud)return{path:e};throw k;}!d.Lc||g&&!b.Vc||(d=d.Lc.root);if(40960===(d.mode&61440)&&(!g||b.Uc)){if(!d.qc.readlink)throw new D(52);
d=d.qc.readlink(d);"/"===d.charAt(0)||(d=Na(e)+"/"+d);a=d+"/"+a.slice(f+1).join("/");continue a}}}return{path:e,node:d}}throw new D(32);}function ub(a){for(var b;;){if(a===a.parent)return a=a.Dc.ud,b?"/"!==a[a.length-1]?`${a}/${b}`:a+b:a;b=b?`${a.name}/${b}`:a.name;a=a.parent}}function vb(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%nb.length}
function eb(a){var b=vb(a.parent.id,a.name);if(nb[b]===a)nb[b]=a.Ic;else for(b=nb[b];b;){if(b.Ic===a){b.Ic=a.Ic;break}b=b.Ic}}function db(a,b){var c=G(a.mode)?(c=wb(a,"x"))?c:a.qc.lookup?0:2:54;if(c)throw new D(c);for(c=nb[vb(a.id,b)];c;c=c.Ic){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.qc.lookup(a,b)}function cb(a,b,c,d){a=new sb(a,b,c,d);b=vb(a.parent.id,a.name);a.Ic=nb[b];return nb[b]=a}function G(a){return 16384===(a&61440)}
function xb(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}function wb(a,b){if(pb)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0}function yb(a,b){if(!G(a.mode))return 54;try{return db(a,b),20}catch(c){}return wb(a,"wx")}function H(a){a=lb[a];if(!a)throw new D(8);return a}
function zb(a,b=-1){a=Object.assign(new rb,a);if(-1==b)a:{for(b=0;4096>=b;b++)if(!lb[b])break a;throw new D(33);}a.fd=b;return lb[b]=a}function Ab(a,b=-1){a=zb(a,b);a.pc?.le?.(a);return a}function Bb(a,b){var c=null?.pc.zc,d=c?null:a;c??=a.qc.zc;if(!c)throw new D(63);c(d,b)}var bb={open(a){a.pc=kb[a.node.rdev].pc;a.pc.open?.(a)},xc(){throw new D(70);}};function Ya(a,b){kb[a]={pc:b}}
function Cb(a,b){var c="/"===b;if(c&&jb)throw new D(10);if(!c&&b){var d=tb(b,{Vc:!1});b=d.path;d=d.node;if(d.Lc)throw new D(10);if(!G(d.mode))throw new D(54);}b={type:a,ye:{},ud:b,Td:[]};a=a.Dc(b);a.Dc=b;b.root=a;c?jb=a:d&&(d.Lc=b,d.Dc&&d.Dc.Td.push(b))}function Db(a,b,c){var d=tb(a,{parent:!0}).node;a=a&&a.match(/([^\/]+|\/)\/*$/)[1];if(!a)throw new D(28);if("."===a||".."===a)throw new D(20);var e=yb(d,a);if(e)throw new D(e);if(!d.qc.Qc)throw new D(63);return d.qc.Qc(d,a,b,c)}
function Eb(a,b=438){return Db(a,b&4095|32768,0)}function J(a){return Db(a,16895,0)}function Fb(a,b,c){"undefined"==typeof c&&(c=b,b=438);return Db(a,b|8192,c)}function Gb(a,b){if(!Qa(a))throw new D(44);var c=tb(b,{parent:!0}).node;if(!c)throw new D(44);b=b&&b.match(/([^\/]+|\/)\/*$/)[1];var d=yb(c,b);if(d)throw new D(d);if(!c.qc.symlink)throw new D(63);c.qc.symlink(c,b,a)}
function Hb(a){var b=tb(a,{parent:!0}).node;if(!b)throw new D(44);a=a&&a.match(/([^\/]+|\/)\/*$/)[1];var c=db(b,a);a:{try{var d=db(b,a)}catch(f){d=f.tc;break a}var e=wb(b,"wx");d=e?e:G(d.mode)?31:0}if(d)throw new D(d);if(!b.qc.unlink)throw new D(63);if(c.Lc)throw new D(10);b.qc.unlink(b,a);eb(c)}function Ib(a,b){a="string"==typeof a?tb(a,{Uc:!0}).node:a;Bb(a,{mode:b&4095|a.mode&-4096,ctime:Date.now(),ke:void 0})}
function Jb(a,b,c=438){if(""===a)throw new D(44);if("string"==typeof b){var d={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090}[b];if("undefined"==typeof d)throw Error(`Unknown file open mode: ${b}`);b=d}c=b&64?c&4095|32768:0;if("object"==typeof a)d=a;else{var e=a.endsWith("/");a=tb(a,{Uc:!(b&131072),Ud:!0});d=a.node;a=a.path}var f=!1;if(b&64)if(d){if(b&128)throw new D(20);}else{if(e)throw new D(31);d=Db(a,c|511,0);f=!0}if(!d)throw new D(44);8192===(d.mode&61440)&&(b&=-513);if(b&65536&&!G(d.mode))throw new D(54);
if(!f&&(e=d?40960===(d.mode&61440)?32:G(d.mode)&&("r"!==xb(b)||b&576)?31:wb(d,xb(b)):44))throw new D(e);if(b&512&&!f){e=d;e="string"==typeof e?tb(e,{Uc:!0}).node:e;if(G(e.mode))throw new D(31);if(32768!==(e.mode&61440))throw new D(28);var g=wb(e,"w");if(g)throw new D(g);Bb(e,{size:0,timestamp:Date.now()})}b&=-131713;e=zb({node:d,path:ub(d),flags:b,seekable:!0,position:0,pc:d.pc,Wd:[],error:!1});e.pc.open&&e.pc.open(e);f&&Ib(d,c&511);!h.logReadFiles||b&1||a in qb||(qb[a]=1);return e}
function Kb(a){if(null===a.fd)throw new D(8);a.Wc&&(a.Wc=null);try{a.pc.close&&a.pc.close(a)}catch(b){throw b;}finally{lb[a.fd]=null}a.fd=null}function Lb(a,b,c){if(null===a.fd)throw new D(8);if(!a.seekable||!a.pc.xc)throw new D(70);if(0!=c&&1!=c&&2!=c)throw new D(28);a.position=a.pc.xc(a,b,c);a.Wd=[]}
function Mb(a,b,c,d,e,f){if(0>d||0>e)throw new D(28);if(null===a.fd)throw new D(8);if(0===(a.flags&2097155))throw new D(8);if(G(a.node.mode))throw new D(31);if(!a.pc.write)throw new D(28);a.seekable&&a.flags&1024&&Lb(a,0,2);var g="undefined"!=typeof e;if(!g)e=a.position;else if(!a.seekable)throw new D(70);b=a.pc.write(a,b,c,d,e,f);g||(a.position+=b);return b}
function Nb(a,b){a="string"==typeof a?a:ub(a);for(b=b.split("/").reverse();b.length;){var c=b.pop();if(c){var d=Ma(a+"/"+c);try{J(d)}catch(e){if(20!=e.tc)throw e;}a=d}}return d}function Ob(a,b,c,d){a=Ma(("string"==typeof a?a:ub(a))+"/"+b);return Eb(a,ib(c,d))}
function Pb(a,b,c,d,e,f){var g=b;a&&(a="string"==typeof a?a:ub(a),g=b?Ma(a+"/"+b):a);a=ib(d,e);g=Eb(g,a);if(c){if("string"==typeof c){b=Array(c.length);d=0;for(e=c.length;d<e;++d)b[d]=c.charCodeAt(d);c=b}Ib(g,a|146);b=Jb(g,577);Mb(b,c,0,c.length,0,f);Kb(b);Ib(g,a)}}
function L(a,b,c,d){a=Ma(("string"==typeof a?a:ub(a))+"/"+b);b=ib(!!c,!!d);L.sd??(L.sd=64);var e=L.sd++<<8|0;Ya(e,{open(f){f.seekable=!1},close(){d?.buffer?.length&&d(10)},read(f,g,k,n){for(var q=0,r=0;r<n;r++){try{var w=c()}catch(x){throw new D(29);}if(void 0===w&&0===q)throw new D(6);if(null===w||void 0===w)break;q++;g[k+r]=w}q&&(f.node.atime=Date.now());return q},write(f,g,k,n){for(var q=0;q<n;q++)try{d(g[k+q])}catch(r){throw new D(29);}n&&(f.node.mtime=f.node.ctime=Date.now());return q}});return Fb(a,
b,e)}function Qb(a){if(!(a.Rd||a.Sd||a.link||a.oc)){if("undefined"!=typeof XMLHttpRequest)throw Error("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");try{a.oc=la(a.url),a.rc=a.oc.length}catch(b){throw new D(29);}}}
function Rb(a,b,c,d,e){class f{Kc=!1;sc=[];Jc=void 0;zd=0;yd=0;get(r){if(!(r>this.length-1||0>r)){var w=r%this.chunkSize;return this.Jc(r/this.chunkSize|0)[w]}}Vd(r){this.Jc=r}Gd(){var r=new XMLHttpRequest;r.open("HEAD",c,!1);r.send(null);if(!(200<=r.status&&300>r.status||304===r.status))throw Error("Couldn't load "+c+". Status: "+r.status);var w=Number(r.getResponseHeader("Content-length")),x,K=(x=r.getResponseHeader("Accept-Ranges"))&&"bytes"===x;r=(x=r.getResponseHeader("Content-Encoding"))&&"gzip"===
x;var F=1048576;K||(F=w);var B=this;B.Vd(N=>{var ea=N*F,T=(N+1)*F-1;T=Math.min(T,w-1);if("undefined"==typeof B.sc[N]){var sd=B.sc;if(ea>T)throw Error("invalid range ("+ea+", "+T+") or no bytes requested!");if(T>w-1)throw Error("only "+w+" bytes available! programmer error!");var I=new XMLHttpRequest;I.open("GET",c,!1);w!==F&&I.setRequestHeader("Range","bytes="+ea+"-"+T);I.responseType="arraybuffer";I.overrideMimeType&&I.overrideMimeType("text/plain; charset=x-user-defined");I.send(null);if(!(200<=
I.status&&300>I.status||304===I.status))throw Error("Couldn't load "+c+". Status: "+I.status);ea=void 0!==I.response?new Uint8Array(I.response||[]):Va(I.responseText||"");sd[N]=ea}if("undefined"==typeof B.sc[N])throw Error("doXHR failed!");return B.sc[N]});if(r||!w)F=w=1,F=w=this.Jc(0).length,na("LazyFiles on gzip forces download of the whole file when length is accessed");this.zd=w;this.yd=F;this.Kc=!0}get length(){this.Kc||this.Gd();return this.zd}get chunkSize(){this.Kc||this.Gd();return this.yd}}
if("undefined"!=typeof XMLHttpRequest){if(!ba)throw"Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc";var g=new f;var k=void 0}else k=c,g=void 0;var n=Ob(a,b,d,e);g?n.oc=g:k&&(n.oc=null,n.url=k);Object.defineProperties(n,{rc:{get:function(){return this.oc.length}}});var q={};Object.keys(n.pc).forEach(r=>{var w=n.pc[r];q[r]=(...x)=>{Qb(n);return w(...x)}});q.read=(r,w,x,K,F)=>{Qb(n);r=r.node.oc;if(F>=r.length)w=0;else{K=Math.min(r.length-
F,K);if(r.slice)for(var B=0;B<K;B++)w[x+B]=r[F+B];else for(B=0;B<K;B++)w[x+B]=r.get(F+B);w=K}return w};q.Zc=()=>{Qb(n);za();throw new D(48);};n.pc=q;return n}
var M={},O=(a,b)=>{if(!a)return"";b=a+b;for(var c=a;!(c>=b)&&p[c];)++c;return Ra.decode(p.subarray(a,c))},Ka=void 0,Sb=0,Tb={},Ub=a=>{a instanceof Ea||"unwind"==a||ha(1,a)},Vb=a=>{qa=a;Ja||0<Sb||(h.onExit?.(a),pa=!0);ha(a,new Ea(a))},Wb=a=>{qa=a;Vb(a)},Xb=()=>{if(!(Ja||0<Sb))try{var a=qa;qa=a;Vb(a)}catch(b){Ub(b)}},Yb=a=>{if(!pa)try{a(),Xb()}catch(b){Ub(b)}},hc=(a,b)=>{Zb=a;$b=b;if(ac)if(bc||=!0,0==a)cc=function(){setTimeout(dc,Math.max(0,ec+b-performance.now())|0)};else if(1==a)cc=function(){fc(dc)};
else if(2==a){if("undefined"==typeof gc)if("undefined"==typeof setImmediate){var c=[];addEventListener("message",d=>{if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);gc=d=>{c.push(d);if(ba){let e;(e=h).setImmediates??(e.setImmediates=[]);h.setImmediates.push(d);postMessage({target:"setimmediate"})}else postMessage("setimmediate","*")}}else gc=setImmediate;cc=function(){gc(dc)}}},qc=(a,b,c,d,e)=>{function f(){return g<ic?(Xb(),!1):!0}ac=a;jc=d;var g=ic;
bc=!1;dc=function(){if(!pa)if(0<kc.length){var k=kc.shift();k.qe(k.Zd);if(lc){var n=lc,q=0==n%1?n-1:Math.floor(n);lc=k.fe?q:(8*n+(q+.5))/9}h.setStatus&&(k=h.statusMessage||"Please wait...",n=lc??0,q=mc.me??0,n?n<q?h.setStatus("{message} ({expected - remaining}/{expected})"):h.setStatus(k):h.setStatus(""));f()&&setTimeout(dc,0)}else if(f())if(nc=nc+1|0,1==Zb&&1<$b&&0!=nc%$b)cc();else{0==Zb&&(ec=performance.now());a:if(!pa){for(k of oc)if(!1===k())break a;Yb(a);for(n of pc)n()}f()&&cc()}};e||(0<b?hc(0,
1E3/b):hc(1,1),cc());if(c)throw"unwind";},bc=!1,cc=null,ic=0,ac=null,jc=0,Zb=0,$b=0,nc=0,kc=[],oc=[],pc=[];function rc(){cc=null;ic++}var sc=0;function fc(a){if("function"==typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===sc)sc=b+1E3/60;else for(;b+2>=sc;)sc+=1E3/60;setTimeout(a,Math.max(sc-b,0))}}
var mc={},ec,dc,gc,lc,tc=[0,"undefined"!=typeof document?document:0,"undefined"!=typeof window?window:0],P=a=>{a=2<a?O(a):a;return tc[a]||("undefined"!=typeof document?document.querySelector(a):null)},uc=a=>0>tc.indexOf(a)?a.getBoundingClientRect():{left:0,top:0},Q;function vc(a){var b=R.vc[a];b.target.removeEventListener(b.uc,b.pd,b.Ac);R.vc.splice(a,1)}function wc(){if(navigator.userActivation?navigator.userActivation.isActive:R.Xc&&R.Jd.Sc){var a=R.Gc;R.Gc=[];for(var b of a)b.bd(...b.jd)}}
function S(a){if(!a.target)return-4;if(a.Bc)a.pd=function(c){++R.Xc;R.Jd=a;wc();a.Cc(c);wc();--R.Xc},a.target.addEventListener(a.uc,a.pd,a.Ac),R.vc.push(a);else for(var b=0;b<R.vc.length;++b)R.vc[b].target==a.target&&R.vc[b].uc==a.uc&&vc(b--);return 0}function xc(a){return a?a==window?"#window":a==screen?"#screen":a?.nodeName||"":""}
var R={$d:0,re:0,Yc:0,Rc:0,gd:0,dd:0,Tc:0,ie:0,ze:0,he:0,pe:0,$c:0,Je:0,cd:0,ve(a,b,c){m.set(m.subarray(b,b+c),a)},Ce(){for(;R.vc.length;)vc(R.vc.length-1);R.Gc=[]},Xc:0,Gc:[],ge(a,b,c){function d(f,g){if(f.length!=g.length)return!1;for(var k in f)if(f[k]!=g[k])return!1;return!0}for(var e of R.Gc)if(e.bd==a&&d(e.jd,c))return;R.Gc.push({bd:a,xd:b,jd:c});R.Gc.sort((f,g)=>f.xd<g.xd)},Ee(a){R.Gc=R.Gc.filter(b=>b.bd!=a)},vc:[],De:(a,b)=>{for(var c=0;c<R.vc.length;++c)R.vc[c].target!=a||b&&b!=R.vc[c].uc||
vc(c--)},fullscreenEnabled(){return document.fullscreenEnabled||document.webkitFullscreenEnabled}},zc=(a,b,c,d,e,f)=>{R.Tc||(R.Tc=yc(256));a={target:P(a),uc:f,Bc:d,Cc:(g=event)=>{var k=g.target.id?g.target.id:"",n=R.Tc;C(xc(g.target),p,n+0,128);C(k,p,n+128,128);Q.get(d)(e,n,b)&&g.preventDefault()},Ac:c};return S(a)},Ac=(a,b,c,d,e,f)=>{R.Yc||(R.Yc=yc(160));a={target:P(a),uc:f,Bc:d,Cc:g=>{var k=R.Yc;y[k>>3]=g.timeStamp;var n=k>>2;t[n+2]=g.location;m[k+12]=g.ctrlKey;m[k+13]=g.shiftKey;m[k+14]=g.altKey;
m[k+15]=g.metaKey;m[k+16]=g.repeat;t[n+5]=g.charCode;t[n+6]=g.keyCode;t[n+7]=g.which;C(g.key||"",p,k+32,32);C(g.code||"",p,k+64,32);C(g.char||"",p,k+96,32);C(g.locale||"",p,k+128,32);Q.get(d)(e,k,b)&&g.preventDefault()},Ac:c};return S(a)},Bc=(a,b,c)=>{y[a>>3]=b.timeStamp;var d=a>>2;t[d+2]=b.screenX;t[d+3]=b.screenY;t[d+4]=b.clientX;t[d+5]=b.clientY;m[a+24]=b.ctrlKey;m[a+25]=b.shiftKey;m[a+26]=b.altKey;m[a+27]=b.metaKey;sa[2*d+14]=b.button;sa[2*d+15]=b.buttons;t[d+8]=b.movementX;t[d+9]=b.movementY;
a=uc(c);t[d+10]=b.clientX-(a.left|0);t[d+11]=b.clientY-(a.top|0)},Cc=(a,b,c,d,e,f)=>{R.Rc||(R.Rc=yc(64));a=P(a);return S({target:a,Sc:"mousemove"!=f&&"mouseenter"!=f&&"mouseleave"!=f,uc:f,Bc:d,Cc:(g=event)=>{Bc(R.Rc,g,a);Q.get(d)(e,R.Rc,b)&&g.preventDefault()},Ac:c})},Dc=(a,b,c,d,e)=>{R.$c||(R.$c=yc(257));return S({target:a,uc:e,Bc:d,Cc:(f=event)=>{var g=R.$c,k=document.pointerLockElement||document.sc||document.Kc||document.Jc;m[g]=!!k;var n=k?.id||"";C(xc(k),p,g+1,128);C(n,p,g+129,128);Q.get(d)(20,
g,b)&&f.preventDefault()},Ac:c})},Ec=(a,b,c,d,e)=>S({target:a,uc:e,Bc:d,Cc:(f=event)=>{Q.get(d)(38,0,b)&&f.preventDefault()},Ac:c}),Fc=(a,b,c,d)=>{R.dd||(R.dd=yc(36));a=P(a);return S({target:a,uc:"resize",Bc:d,Cc:(e=event)=>{if(e.target==a){var f=document.body;if(f){var g=R.dd;t[g>>2]=0;t[g+4>>2]=f.clientWidth;t[g+8>>2]=f.clientHeight;t[g+12>>2]=innerWidth;t[g+16>>2]=innerHeight;t[g+20>>2]=outerWidth;t[g+24>>2]=outerHeight;t[g+28>>2]=pageXOffset|0;t[g+32>>2]=pageYOffset|0;Q.get(d)(10,g,b)&&e.preventDefault()}}},
Ac:c})},Gc=(a,b,c,d,e,f)=>{R.cd||(R.cd=yc(1552));a=P(a);return S({target:a,Sc:"touchstart"==f||"touchend"==f,uc:f,Bc:d,Cc:g=>{var k={},n=g.touches;for(var q of n)q.rd=q.wd=0,k[q.identifier]=q;for(var r of g.changedTouches)r.rd=1,k[r.identifier]=r;for(var w of g.targetTouches)k[w.identifier].wd=1;n=R.cd;y[n>>3]=g.timeStamp;m[n+12]=g.ctrlKey;m[n+13]=g.shiftKey;m[n+14]=g.altKey;m[n+15]=g.metaKey;q=n+16;r=uc(a);w=0;for(let x of Object.values(k))if(k=q>>2,t[k]=x.identifier,t[k+1]=x.screenX,t[k+2]=x.screenY,
t[k+3]=x.clientX,t[k+4]=x.clientY,t[k+5]=x.pageX,t[k+6]=x.pageY,m[q+28]=x.rd,m[q+29]=x.wd,t[k+8]=x.clientX-(r.left|0),t[k+9]=x.clientY-(r.top|0),q+=48,31<++w)break;t[n+8>>2]=w;Q.get(d)(e,n,b)&&g.preventDefault()},Ac:c})},U,Hc=a=>{var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=(c,d)=>b.vertexAttribDivisorANGLE(c,d),a.drawArraysInstanced=(c,d,e,f)=>b.drawArraysInstancedANGLE(c,d,e,f),a.drawElementsInstanced=(c,d,e,f,g)=>b.drawElementsInstancedANGLE(c,d,e,f,g))},Ic=a=>{var b=
a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=()=>b.createVertexArrayOES(),a.deleteVertexArray=c=>b.deleteVertexArrayOES(c),a.bindVertexArray=c=>b.bindVertexArrayOES(c),a.isVertexArray=c=>b.isVertexArrayOES(c))},Jc=a=>{var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=(c,d)=>b.drawBuffersWEBGL(c,d))},Kc=a=>{var b="ANGLE_instanced_arrays EXT_blend_minmax EXT_disjoint_timer_query EXT_frag_depth EXT_shader_texture_lod EXT_sRGB OES_element_index_uint OES_fbo_render_mipmap OES_standard_derivatives OES_texture_float OES_texture_half_float OES_texture_half_float_linear OES_vertex_array_object WEBGL_color_buffer_float WEBGL_depth_texture WEBGL_draw_buffers EXT_color_buffer_float EXT_conservative_depth EXT_disjoint_timer_query_webgl2 EXT_texture_norm16 NV_shader_noperspective_interpolation WEBGL_clip_cull_distance EXT_clip_control EXT_color_buffer_half_float EXT_depth_clamp EXT_float_blend EXT_polygon_offset_clamp EXT_texture_compression_bptc EXT_texture_compression_rgtc EXT_texture_filter_anisotropic KHR_parallel_shader_compile OES_texture_float_linear WEBGL_blend_func_extended WEBGL_compressed_texture_astc WEBGL_compressed_texture_etc WEBGL_compressed_texture_etc1 WEBGL_compressed_texture_s3tc WEBGL_compressed_texture_s3tc_srgb WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_lose_context WEBGL_multi_draw WEBGL_polygon_mode".split(" ");
return(a.getSupportedExtensions()||[]).filter(c=>b.includes(c))},Lc=1,Mc=[],V=[],Nc=[],Oc=[],Pc=[],W=[],Qc=[],Rc=[],Sc=[],Tc={},Uc=4,Vc=0,Wc=a=>{for(var b=Lc++,c=a.length;c<b;c++)a[c]=null;return b},Xc=(a,b,c,d)=>{for(var e=0;e<a;e++){var f=U[c](),g=f&&Wc(d);f?(f.name=g,d[g]=f):X||=1282;t[b+4*e>>2]=g}},Zc=(a,b)=>{a.sc||(a.sc=a.getContext,a.getContext=function(d,e){e=a.sc(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=1<b.td?a.getContext("webgl2",b):a.getContext("webgl",b);
return c?Yc(c,b):0},Yc=(a,b)=>{var c=Wc(Rc),d={handle:c,attributes:b,version:b.td,hd:a};a.canvas&&(a.canvas.Xd=d);Rc[c]=d;("undefined"==typeof b.od||b.od)&&$c(d);return c},$c=a=>{a||=Y;if(!a.Md){a.Md=!0;var b=a.hd;b.xe=b.getExtension("WEBGL_multi_draw");b.oe=b.getExtension("EXT_polygon_offset_clamp");b.ne=b.getExtension("EXT_clip_control");b.Ke=b.getExtension("WEBGL_polygon_mode");Hc(b);Ic(b);Jc(b);b.je=b.getExtension("WEBGL_draw_instanced_base_vertex_base_instance");b.ue=b.getExtension("WEBGL_multi_draw_instanced_base_vertex_base_instance");
2<=a.version&&(b.md=b.getExtension("EXT_disjoint_timer_query_webgl2"));if(2>a.version||!b.md)b.md=b.getExtension("EXT_disjoint_timer_query");Kc(b).forEach(c=>{c.includes("lose_context")||c.includes("debug")||b.getExtension(c)})}},X,Y,ad=(a,b,c,d,e,f)=>{a={target:P(a),uc:f,Bc:d,Cc:(g=event)=>{Q.get(d)(e,0,b)&&g.preventDefault()},Ac:c};S(a)},bd=(a,b,c,d)=>{R.gd||(R.gd=yc(96));return S({target:a,Sc:!0,uc:"wheel",Bc:d,Cc:(e=event)=>{var f=R.gd;Bc(f,e,a);y[f+64>>3]=e.deltaX;y[f+72>>3]=e.deltaY;y[f+80>>
3]=e.deltaZ;t[f+88>>2]=e.deltaMode;Q.get(d)(9,f,b)&&e.preventDefault()},Ac:c})},cd=["default","low-power","high-performance"],dd={},fd=()=>{if(!ed){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.language||"C").replace("-","_")+".UTF-8",_:fa||"./this.program"},b;for(b in dd)void 0===dd[b]?delete a[b]:a[b]=dd[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);ed=c}return ed},ed,gd=(a,b,c,d)=>{for(var e=0,f=0;f<c;f++){var g=u[b>>
2],k=u[b+4>>2];b+=8;g=Mb(a,m,g,k,d);if(0>g)return-1;e+=g;if(g<k)break;"undefined"!=typeof d&&(d+=g)}return e},hd=[],jd=()=>{var a=Kc(U);return a=a.concat(a.map(b=>"GL_"+b))},kd=(a,b)=>{if(b){var c=void 0;switch(a){case 36346:c=1;break;case 36344:return;case 34814:case 36345:c=0;break;case 34466:var d=U.getParameter(34467);c=d?d.length:0;break;case 33309:if(2>Y.version){X||=1282;return}c=jd().length;break;case 33307:case 33308:if(2>Y.version){X||=1280;return}c=33307==a?3:0}if(void 0===c)switch(d=U.getParameter(a),
typeof d){case "number":c=d;break;case "boolean":c=d?1:0;break;case "string":X||=1280;return;case "object":if(null===d)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 36662:case 36663:case 35053:case 35055:case 36010:case 35097:case 35869:case 32874:case 36389:case 35983:case 35368:case 34068:c=0;break;default:X||=1280;return}else{if(d instanceof Float32Array||d instanceof Uint32Array||d instanceof Int32Array||d instanceof Array){for(a=0;a<d.length;++a)t[b+
4*a>>2]=d[a];return}try{c=d.name|0}catch(e){X||=1280;l(`GL_INVALID_ENUM in glGet${0}v: Unknown object returned from WebGL getParameter(${a})! (error: ${e})`);return}}break;default:X||=1280;l(`GL_INVALID_ENUM in glGet${0}v: Native code calling glGet${0}v(${a}) and it returns ${d} of type ${typeof d}!`);return}t[b>>2]=c}else X||=1281},ld=a=>{var b=Ua(a)+1,c=yc(b);c&&C(a,p,c,b);return c},md=a=>"]"==a.slice(-1)&&a.lastIndexOf("["),nd=a=>{a-=5120;return 0==a?m:1==a?p:2==a?sa:4==a?t:6==a?v:5==a||28922==
a||28520==a||30779==a||30782==a?u:ta},Z=a=>{var b=U.Kd;if(b){var c=b.Mc[a];"number"==typeof c&&(b.Mc[a]=c=U.getUniformLocation(b,b.Hd[a]+(0<c?`[${c}]`:"")));return c}X||=1282},od=[],pd=[],rd=a=>{var b=Ua(a)+1,c=qd(b);C(a,p,c,b);return c},vd=a=>{var b=td();a();ud(b)};nb=Array(4096);Cb(E,"/");J("/tmp");J("/home");J("/home/web_user");
(function(){J("/dev");Ya(259,{read:()=>0,write:(d,e,f,g)=>g,xc:()=>0});Fb("/dev/null",259);Xa(1280,$a);Xa(1536,ab);Fb("/dev/tty",1280);Fb("/dev/tty1",1536);var a=new Uint8Array(1024),b=0,c=()=>{0===b&&(Pa(a),b=a.byteLength);return a[--b]};L("/dev","random",c);L("/dev","urandom",c);J("/dev/shm");J("/dev/shm/tmp")})();
(function(){J("/proc");var a=J("/proc/self");J("/proc/self/fd");Cb({Dc(){var b=cb(a,"fd",16895,73);b.pc={xc:E.pc.xc};b.qc={lookup(c,d){c=+d;var e=H(c);c={parent:null,Dc:{ud:"fake"},qc:{readlink:()=>e.path},id:c+1};return c.parent=c},readdir(){return Array.from(lb.entries()).filter(([,c])=>c).map(([c])=>c.toString())}};return b}},"/proc/self/fd")})();E.nd=new D(44);E.nd.stack="<generic error, no stack>";h.requestAnimationFrame=fc;h.pauseMainLoop=rc;
h.resumeMainLoop=function(){ic++;var a=Zb,b=$b,c=ac;ac=null;qc(c,0,!1,jc,!0);hc(a,b);cc()};h.preMainLoop&&oc.push(h.preMainLoop);h.postMainLoop&&pc.push(h.postMainLoop);for(let a=0;32>a;++a)hd.push(Array(a));for(var wd=new Float32Array(288),xd=0;288>=xd;++xd)od[xd]=wd.subarray(0,xd);var yd=new Int32Array(288);for(xd=0;288>=xd;++xd)pd[xd]=yd.subarray(0,xd);h.noExitRuntime&&(Ja=h.noExitRuntime);h.preloadPlugins&&(gb=h.preloadPlugins);h.print&&(na=h.print);h.printErr&&(l=h.printErr);
h.wasmBinary&&(oa=h.wasmBinary);h.arguments&&(da=h.arguments);h.thisProgram&&(fa=h.thisProgram);h.addRunDependency=xa;h.removeRunDependency=ya;h.FS_createPreloadedFile=(a,b,c,d,e,f,g,k,n,q)=>{function r(K){function F(B){q?.();k||Pb(a,b,B,d,e,n);f?.();ya(x)}hb(K,w,F,()=>{g?.();ya(x)})||F(K)}var w=b?Qa(Ma(a+"/"+b)):a,x=`cp ${w}`;xa(x);"string"==typeof c?fb(c).then(r,g):r(c)};h.FS_unlink=(...a)=>Hb(...a);h.FS_createPath=(...a)=>Nb(...a);h.FS_createDevice=(...a)=>L(...a);h.FS_createDataFile=(...a)=>Pb(...a);
h.FS_createLazyFile=(...a)=>Rb(...a);
var zd,Ad,Bd,Cd,Dd,Ed,Fd,yc,ud,qd,td,Gd={N:function(a,b,c){Ka=c;try{var d=H(a);switch(b){case 0:var e=A();if(0>e)break;for(;lb[e];)e++;return Ab(d,e).fd;case 1:case 2:return 0;case 3:return d.flags;case 4:return e=A(),d.flags|=e,0;case 12:return e=A(),sa[e+0>>1]=2,0;case 13:case 14:return 0}return-28}catch(f){if("undefined"==typeof M||"ErrnoError"!==f.name)throw f;return-f.tc}},lb:function(a,b){try{var c=H(a),d=c.node,e=c.pc.wc;a=e?c:d;e??=d.qc.wc;if(!e)throw new D(63);var f=e(a);t[b>>2]=f.dev;t[b+
4>>2]=f.mode;u[b+8>>2]=f.nlink;t[b+12>>2]=f.uid;t[b+16>>2]=f.gid;t[b+20>>2]=f.rdev;z[b+24>>3]=BigInt(f.size);t[b+32>>2]=4096;t[b+36>>2]=f.blocks;var g=f.atime.getTime(),k=f.mtime.getTime(),n=f.ctime.getTime();z[b+40>>3]=BigInt(Math.floor(g/1E3));u[b+48>>2]=g%1E3*1E6;z[b+56>>3]=BigInt(Math.floor(k/1E3));u[b+64>>2]=k%1E3*1E6;z[b+72>>3]=BigInt(Math.floor(n/1E3));u[b+80>>2]=n%1E3*1E6;z[b+88>>3]=BigInt(f.ino);return 0}catch(q){if("undefined"==typeof M||"ErrnoError"!==q.name)throw q;return-q.tc}},Na:function(a,
b,c){Ka=c;try{var d=H(a);switch(b){case 21509:return d.tty?0:-59;case 21505:if(!d.tty)return-59;if(d.tty.Ec.Od){a=[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0];var e=A();t[e>>2]=25856;t[e+4>>2]=5;t[e+8>>2]=191;t[e+12>>2]=35387;for(var f=0;32>f;f++)m[e+f+17]=a[f]||0}return 0;case 21510:case 21511:case 21512:return d.tty?0:-59;case 21506:case 21507:case 21508:if(!d.tty)return-59;if(d.tty.Ec.Pd)for(e=A(),a=[],f=0;32>f;f++)a.push(m[e+f+17]);return 0;case 21519:if(!d.tty)return-59;
e=A();return t[e>>2]=0;case 21520:return d.tty?-28:-59;case 21531:e=A();if(!d.pc.Nd)throw new D(59);return d.pc.Nd(d,b,e);case 21523:if(!d.tty)return-59;d.tty.Ec.Qd&&(f=[24,80],e=A(),sa[e>>1]=f[0],sa[e+2>>1]=f[1]);return 0;case 21524:return d.tty?0:-59;case 21515:return d.tty?0:-59;default:return-28}}catch(g){if("undefined"==typeof M||"ErrnoError"!==g.name)throw g;return-g.tc}},va:function(a,b,c,d){Ka=d;try{b=O(b);var e=b;if("/"===e.charAt(0))b=e;else{var f=-100===a?"/":H(a).path;if(0==e.length)throw new D(44);
b=f+"/"+e}var g=d?A():0;return Jb(b,c,g).fd}catch(k){if("undefined"==typeof M||"ErrnoError"!==k.name)throw k;return-k.tc}},Ra:()=>za(""),_b:a=>{do{var b=u[a>>2];a+=4;var c=u[a>>2];a+=4;var d=u[a>>2];a+=4;b=O(b);Nb("/",Na(b));Pb(b,null,m.subarray(d,d+c),!0,!0,!0)}while(u[a>>2])},ib:()=>{Ja=!1;Sb=0},jb:(a,b)=>{Tb[a]&&(clearTimeout(Tb[a].id),delete Tb[a]);if(!b)return 0;var c=setTimeout(()=>{delete Tb[a];Yb(()=>Fd(a,performance.now()))},b);Tb[a]={id:c,Ie:b};return 0},mb:function(a,b,c){if(!(0<=a&&3>=
a))return 28;z[c>>3]=BigInt(Math.round(1E6*(0===a?Date.now():performance.now())));return 0},Va:()=>{rc();ac=null},la:()=>"number"==typeof devicePixelRatio&&devicePixelRatio||1,qa:(a,b,c)=>{a=P(a);if(!a)return-4;a=uc(a);y[b>>3]=a.width;y[c>>3]=a.height;return 0},Wa:()=>performance.now(),$a:(a,b)=>{function c(d){Q.get(a)(d,b)&&requestAnimationFrame(c)}return requestAnimationFrame(c)},fb:a=>{var b=p.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);
a:{d=(Math.min(2147483648,65536*Math.ceil(Math.max(a,d)/65536))-ra.buffer.byteLength+65535)/65536|0;try{ra.grow(d);ua();var e=1;break a}catch(f){}e=void 0}if(e)return!0}return!1},Q:(a,b,c,d)=>zc(a,b,c,d,12,"blur"),ja:(a,b,c)=>{a=P(a);if(!a)return-4;a.width=b;a.height=c;return 0},R:(a,b,c,d)=>zc(a,b,c,d,13,"focus"),_:(a,b,c,d)=>Ac(a,b,c,d,2,"keydown"),Y:(a,b,c,d)=>Ac(a,b,c,d,1,"keypress"),Z:(a,b,c,d)=>Ac(a,b,c,d,3,"keyup"),ab:(a,b,c)=>{a=Q.get(a);qc(a,b,c)},ea:(a,b,c,d)=>Cc(a,b,c,d,5,"mousedown"),
ba:(a,b,c,d)=>Cc(a,b,c,d,33,"mouseenter"),aa:(a,b,c,d)=>Cc(a,b,c,d,34,"mouseleave"),ca:(a,b,c,d)=>Cc(a,b,c,d,8,"mousemove"),da:(a,b,c,d)=>Cc(a,b,c,d,6,"mouseup"),T:(a,b,c,d)=>{if(!document||!document.body||!(document.body.requestPointerLock||document.body.sc||document.body.Kc||document.body.Jc))return-1;a=P(a);if(!a)return-4;Dc(a,b,c,d,"mozpointerlockchange");Dc(a,b,c,d,"webkitpointerlockchange");Dc(a,b,c,d,"mspointerlockchange");return Dc(a,b,c,d,"pointerlockchange")},S:(a,b,c,d)=>{if(!document||
!(document.body.requestPointerLock||document.body.sc||document.body.Kc||document.body.Jc))return-1;a=P(a);if(!a)return-4;Ec(a,b,c,d,"mozpointerlockerror");Ec(a,b,c,d,"webkitpointerlockerror");Ec(a,b,c,d,"mspointerlockerror");return Ec(a,b,c,d,"pointerlockerror")},ma:(a,b,c,d)=>Fc(a,b,c,d),U:(a,b,c,d)=>Gc(a,b,c,d,25,"touchcancel"),V:(a,b,c,d)=>Gc(a,b,c,d,23,"touchend"),W:(a,b,c,d)=>Gc(a,b,c,d,24,"touchmove"),X:(a,b,c,d)=>Gc(a,b,c,d,22,"touchstart"),P:(a,b,c,d)=>{ad(a,b,c,d,31,"webglcontextlost");return 0},
O:(a,b,c,d)=>{ad(a,b,c,d,32,"webglcontextrestored");return 0},$:(a,b,c,d)=>(a=P(a))?"undefined"!=typeof a.onwheel?bd(a,b,c,d):-1:-4,qb:(a,b)=>{var c=b>>2;b={alpha:!!m[b+0],depth:!!m[b+1],stencil:!!m[b+2],antialias:!!m[b+3],premultipliedAlpha:!!m[b+4],preserveDrawingBuffer:!!m[b+5],powerPreference:cd[t[c+2]],failIfMajorPerformanceCaveat:!!m[b+12],td:t[c+4],we:t[c+5],od:m[b+24],Ld:m[b+25],Ae:t[c+7],Fe:m[b+32]};a=P(a);return!a||b.Ld?0:Zc(a,b)},hb:a=>{Y=Rc[a];h.ctx=U=Y?.hd;return!a||U?0:-5},ob:(a,b)=>
{var c=0,d=0,e;for(e of fd()){var f=b+c;u[a+d>>2]=f;c+=C(e,p,f,Infinity)+1;d+=4}return 0},pb:(a,b)=>{var c=fd();u[a>>2]=c.length;a=0;for(var d of c)a+=Ua(d)+1;u[b>>2]=a;return 0},p:function(a){try{var b=H(a);Kb(b);return 0}catch(c){if("undefined"==typeof M||"ErrnoError"!==c.name)throw c;return c.tc}},eb:function(a,b){try{var c=H(a);m[b]=c.tty?2:G(c.mode)?3:40960===(c.mode&61440)?7:4;sa[b+2>>1]=0;z[b+8>>3]=BigInt(0);z[b+16>>3]=BigInt(0);return 0}catch(d){if("undefined"==typeof M||"ErrnoError"!==d.name)throw d;
return d.tc}},kb:function(a,b,c,d,e){d=-9007199254740992>d||9007199254740992<d?NaN:Number(d);try{if(isNaN(d))return 61;var f=H(a),g=gd(f,b,c,d);u[e>>2]=g;return 0}catch(k){if("undefined"==typeof M||"ErrnoError"!==k.name)throw k;return k.tc}},H:function(a,b,c,d){try{a:{var e=H(a);a=b;for(var f,g=b=0;g<c;g++){var k=u[a>>2],n=u[a+4>>2];a+=8;var q=e,r=k,w=n,x=f,K=m;if(0>w||0>x)throw new D(28);if(null===q.fd)throw new D(8);if(1===(q.flags&2097155))throw new D(8);if(G(q.node.mode))throw new D(31);if(!q.pc.read)throw new D(28);
var F="undefined"!=typeof x;if(!F)x=q.position;else if(!q.seekable)throw new D(70);var B=q.pc.read(q,K,r,w,x);F||(q.position+=B);var N=B;if(0>N){var ea=-1;break a}b+=N;if(N<n)break;"undefined"!=typeof f&&(f+=N)}ea=b}u[d>>2]=ea;return 0}catch(T){if("undefined"==typeof M||"ErrnoError"!==T.name)throw T;return T.tc}},Ca:function(a,b,c,d){b=-9007199254740992>b||9007199254740992<b?NaN:Number(b);try{if(isNaN(b))return 61;var e=H(a);Lb(e,b,c);z[d>>3]=BigInt(e.position);e.Wc&&0===b&&0===c&&(e.Wc=null);return 0}catch(f){if("undefined"==
typeof M||"ErrnoError"!==f.name)throw f;return f.tc}},t:function(a,b,c,d){try{var e=H(a),f=gd(e,b,c);u[d>>2]=f;return 0}catch(g){if("undefined"==typeof M||"ErrnoError"!==g.name)throw g;return g.tc}},v:a=>U.activeTexture(a),q:(a,b)=>{U.attachShader(V[a],W[b])},b:(a,b)=>{35051==a?U.ld=b:35052==a&&(U.Hc=b);U.bindBuffer(a,Mc[b])},ka:(a,b,c)=>{U.bindBufferBase(a,b,Mc[c])},Ub:(a,b,c,d,e)=>{U.bindBufferRange(a,b,Mc[c],d,e)},f:(a,b)=>{U.bindFramebuffer(a,Nc[b])},xa:(a,b)=>{U.bindRenderbuffer(a,Oc[b])},u:(a,
b)=>{U.bindSampler(a,Sc[b])},g:(a,b)=>{U.bindTexture(a,Pc[b])},M:a=>{U.bindVertexArray(Qc[a])},ra:(a,b,c,d)=>U.blendColor(a,b,c,d),sa:(a,b)=>U.blendEquationSeparate(a,b),ta:(a,b,c,d)=>U.blendFuncSeparate(a,b,c,d),Bb:(a,b,c,d,e,f,g,k,n,q)=>U.blitFramebuffer(a,b,c,d,e,f,g,k,n,q),Ka:(a,b,c,d)=>{2<=Y.version?c&&b?U.bufferData(a,p,d,c,b):U.bufferData(a,b,d):U.bufferData(a,c?p.subarray(c,c+b):b,d)},I:(a,b,c,d)=>{2<=Y.version?c&&U.bufferSubData(a,b,p,d,c):U.bufferSubData(a,b,p.subarray(d,d+c))},rb:a=>U.checkFramebufferStatus(a),
Yb:(a,b,c,d)=>U.clearBufferfi(a,b,c,d),w:(a,b,c)=>{U.clearBufferfv(a,b,v,c>>2)},Xb:(a,b,c)=>{U.clearBufferiv(a,b,t,c>>2)},l:(a,b,c,d)=>{U.colorMask(!!a,!!b,!!c,!!d)},ub:a=>{U.compileShader(W[a])},Ga:(a,b,c,d,e,f,g,k,n)=>{2<=Y.version?U.Hc||!k?U.compressedTexSubImage2D(a,b,c,d,e,f,g,k,n):U.compressedTexSubImage2D(a,b,c,d,e,f,g,p,n,k):U.compressedTexSubImage2D(a,b,c,d,e,f,g,p.subarray(n,n+k))},Fa:(a,b,c,d,e,f,g,k,n,q,r)=>{U.Hc?U.compressedTexSubImage3D(a,b,c,d,e,f,g,k,n,q,r):U.compressedTexSubImage3D(a,
b,c,d,e,f,g,k,n,p,r,q)},Da:()=>{var a=Wc(V),b=U.createProgram();b.name=a;b.Pc=b.Nc=b.Oc=0;b.ed=1;V[a]=b;return a},wb:a=>{var b=Wc(W);W[b]=U.createShader(a);return b},pa:a=>U.cullFace(a),xb:(a,b)=>{for(var c=0;c<a;c++){var d=t[b+4*c>>2],e=Mc[d];e&&(U.deleteBuffer(e),e.name=0,Mc[d]=null,d==U.ld&&(U.ld=0),d==U.Hc&&(U.Hc=0))}},r:(a,b)=>{for(var c=0;c<a;++c){var d=t[b+4*c>>2],e=Nc[d];e&&(U.deleteFramebuffer(e),e.name=0,Nc[d]=null)}},i:a=>{if(a){var b=V[a];b?(U.deleteProgram(b),b.name=0,V[a]=null):X||=
1281}},J:(a,b)=>{for(var c=0;c<a;c++){var d=t[b+4*c>>2],e=Oc[d];e&&(U.deleteRenderbuffer(e),e.name=0,Oc[d]=null)}},K:(a,b)=>{for(var c=0;c<a;c++){var d=t[b+4*c>>2],e=Sc[d];e&&(U.deleteSampler(e),e.name=0,Sc[d]=null)}},h:a=>{if(a){var b=W[a];b?(U.deleteShader(b),W[a]=null):X||=1281}},m:(a,b)=>{for(var c=0;c<a;c++){var d=t[b+4*c>>2],e=Pc[d];e&&(U.deleteTexture(e),e.name=0,Pc[d]=null)}},Ma:(a,b)=>{for(var c=0;c<a;c++){var d=t[b+4*c>>2];U.deleteVertexArray(Qc[d]);Qc[d]=null}},n:a=>U.depthFunc(a),o:a=>
{U.depthMask(!!a)},c:a=>U.disable(a),na:a=>{U.disableVertexAttribArray(a)},Db:(a,b,c)=>{U.drawArrays(a,b,c)},Eb:(a,b,c,d)=>{U.drawArraysInstanced(a,b,c,d)},A:(a,b)=>{for(var c=hd[a],d=0;d<a;d++)c[d]=t[b+4*d>>2];U.drawBuffers(c)},Gb:(a,b,c,d)=>{U.drawElements(a,b,c,d)},Fb:(a,b,c,d,e)=>{U.drawElementsInstanced(a,b,c,d,e)},e:a=>U.enable(a),Qb:a=>{U.enableVertexAttribArray(a)},z:(a,b,c,d)=>{U.framebufferRenderbuffer(a,b,c,Oc[d])},ha:(a,b,c,d,e)=>{U.framebufferTexture2D(a,b,c,Pc[d],e)},sb:(a,b,c,d,e)=>
{U.framebufferTextureLayer(a,b,Pc[c],d,e)},oa:a=>U.frontFace(a),La:(a,b)=>{Xc(a,b,"createBuffer",Mc)},L:(a,b)=>{Xc(a,b,"createFramebuffer",Nc)},ya:(a,b)=>{Xc(a,b,"createRenderbuffer",Oc)},Ea:(a,b)=>{Xc(a,b,"createSampler",Sc)},Ja:(a,b)=>{Xc(a,b,"createTexture",Pc)},Pa:(a,b)=>{Xc(a,b,"createVertexArray",Qc)},za:(a,b)=>U.getAttribLocation(V[a],O(b)),a:(a,b)=>kd(a,b),Ba:(a,b,c,d)=>{a=U.getProgramInfoLog(V[a]);null===a&&(a="(unknown error)");b=0<b&&d?C(a,p,d,b):0;c&&(t[c>>2]=b)},C:(a,b,c)=>{if(c)if(a>=
Lc)X||=1281;else if(a=V[a],35716==b)a=U.getProgramInfoLog(a),null===a&&(a="(unknown error)"),t[c>>2]=a.length+1;else if(35719==b){if(!a.Pc){var d=U.getProgramParameter(a,35718);for(b=0;b<d;++b)a.Pc=Math.max(a.Pc,U.getActiveUniform(a,b).name.length+1)}t[c>>2]=a.Pc}else if(35722==b){if(!a.Nc)for(d=U.getProgramParameter(a,35721),b=0;b<d;++b)a.Nc=Math.max(a.Nc,U.getActiveAttrib(a,b).name.length+1);t[c>>2]=a.Nc}else if(35381==b){if(!a.Oc)for(d=U.getProgramParameter(a,35382),b=0;b<d;++b)a.Oc=Math.max(a.Oc,
U.getActiveUniformBlockName(a,b).length+1);t[c>>2]=a.Oc}else t[c>>2]=U.getProgramParameter(a,b);else X||=1281},tb:(a,b,c,d)=>{a=U.getShaderInfoLog(W[a]);null===a&&(a="(unknown error)");b=0<b&&d?C(a,p,d,b):0;c&&(t[c>>2]=b)},ia:(a,b,c)=>{c?35716==b?(a=U.getShaderInfoLog(W[a]),null===a&&(a="(unknown error)"),t[c>>2]=a?a.length+1:0):35720==b?(a=U.getShaderSource(W[a]),t[c>>2]=a?a.length+1:0):t[c>>2]=U.getShaderParameter(W[a],b):X||=1281},Qa:(a,b)=>{if(2>Y.version)return X||=1282,0;var c=Tc[a];if(c)return 0>
b||b>=c.length?(X||=1281,0):c[b];switch(a){case 7939:return c=jd().map(ld),c=Tc[a]=c,0>b||b>=c.length?(X||=1281,0):c[b];default:return X||=1280,0}},B:(a,b)=>{b=O(b);if(a=V[a]){var c=a,d=c.Mc,e=c.Id,f;if(!d){c.Mc=d={};c.Hd={};var g=U.getProgramParameter(c,35718);for(f=0;f<g;++f){var k=U.getActiveUniform(c,f);var n=k.name;k=k.size;var q=md(n);q=0<q?n.slice(0,q):n;var r=c.ed;c.ed+=k;e[q]=[k,r];for(n=0;n<k;++n)d[r]=n,c.Hd[r++]=q}}c=a.Mc;d=0;e=b;f=md(b);0<f&&(d=parseInt(b.slice(f+1))>>>0,e=b.slice(0,f));
if((e=a.Id[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||U.getUniformLocation(a,b)))return d}else X||=1281;return-1},Ab:(a,b,c)=>{for(var d=hd[b],e=0;e<b;e++)d[e]=t[c+4*e>>2];U.invalidateFramebuffer(a,d)},D:a=>{a=V[a];U.linkProgram(a);a.Mc=0;a.Id={}},Oa:(a,b)=>{3317==a?Uc=b:3314==a&&(Vc=b);U.pixelStorei(a,b)},ua:(a,b)=>U.polygonOffset(a,b),Cb:a=>U.readBuffer(a),wa:(a,b,c,d,e)=>U.renderbufferStorageMultisample(a,b,c,d,e),E:(a,b,c)=>{U.samplerParameterf(Sc[a],b,c)},d:(a,b,c)=>{U.samplerParameteri(Sc[a],b,c)},x:(a,
b,c,d)=>U.scissor(a,b,c,d),vb:(a,b,c,d)=>{for(var e="",f=0;f<b;++f)e+=O(u[c+4*f>>2],d?u[d+4*f>>2]:void 0);U.shaderSource(W[a],e)},zb:(a,b,c)=>U.stencilFunc(a,b,c),Wb:(a,b,c,d)=>U.stencilFuncSeparate(a,b,c,d),k:a=>U.stencilMask(a),yb:(a,b,c)=>U.stencilOp(a,b,c),Vb:(a,b,c,d)=>U.stencilOpSeparate(a,b,c,d),Ia:(a,b,c,d,e)=>U.texStorage2D(a,b,c,d,e),Ha:(a,b,c,d,e,f)=>U.texStorage3D(a,b,c,d,e,f),G:(a,b,c,d,e,f,g,k,n)=>{if(2<=Y.version){if(U.Hc){U.texSubImage2D(a,b,c,d,e,f,g,k,n);return}if(n){var q=nd(k);
U.texSubImage2D(a,b,c,d,e,f,g,k,q,n>>>31-Math.clz32(q.BYTES_PER_ELEMENT));return}}if(n){q=nd(k);var r=f*((Vc||e)*({5:3,6:4,8:2,29502:3,29504:4,26917:2,26918:2,29846:3,29847:4}[g-6402]||1)*q.BYTES_PER_ELEMENT+Uc-1&-Uc);n=q.subarray(n>>>31-Math.clz32(q.BYTES_PER_ELEMENT),n+r>>>31-Math.clz32(q.BYTES_PER_ELEMENT))}else n=null;U.texSubImage2D(a,b,c,d,e,f,g,k,n)},F:(a,b,c,d,e,f,g,k,n,q,r)=>{if(U.Hc)U.texSubImage3D(a,b,c,d,e,f,g,k,n,q,r);else if(r){var w=nd(q);U.texSubImage3D(a,b,c,d,e,f,g,k,n,q,w,r>>>31-
Math.clz32(w.BYTES_PER_ELEMENT))}else U.texSubImage3D(a,b,c,d,e,f,g,k,n,q,null)},Pb:(a,b,c)=>{if(2<=Y.version)b&&U.uniform1fv(Z(a),v,c>>2,b);else{if(288>=b)for(var d=od[b],e=0;e<b;++e)d[e]=v[c+4*e>>2];else d=v.subarray(c>>2,c+4*b>>2);U.uniform1fv(Z(a),d)}},Aa:(a,b)=>{U.uniform1i(Z(a),b)},Lb:(a,b,c)=>{if(2<=Y.version)b&&U.uniform1iv(Z(a),t,c>>2,b);else{if(288>=b)for(var d=pd[b],e=0;e<b;++e)d[e]=t[c+4*e>>2];else d=t.subarray(c>>2,c+4*b>>2);U.uniform1iv(Z(a),d)}},Ob:(a,b,c)=>{if(2<=Y.version)b&&U.uniform2fv(Z(a),
v,c>>2,2*b);else{if(144>=b){b*=2;for(var d=od[b],e=0;e<b;e+=2)d[e]=v[c+4*e>>2],d[e+1]=v[c+(4*e+4)>>2]}else d=v.subarray(c>>2,c+8*b>>2);U.uniform2fv(Z(a),d)}},Kb:(a,b,c)=>{if(2<=Y.version)b&&U.uniform2iv(Z(a),t,c>>2,2*b);else{if(144>=b){b*=2;for(var d=pd[b],e=0;e<b;e+=2)d[e]=t[c+4*e>>2],d[e+1]=t[c+(4*e+4)>>2]}else d=t.subarray(c>>2,c+8*b>>2);U.uniform2iv(Z(a),d)}},Nb:(a,b,c)=>{if(2<=Y.version)b&&U.uniform3fv(Z(a),v,c>>2,3*b);else{if(96>=b){b*=3;for(var d=od[b],e=0;e<b;e+=3)d[e]=v[c+4*e>>2],d[e+1]=
v[c+(4*e+4)>>2],d[e+2]=v[c+(4*e+8)>>2]}else d=v.subarray(c>>2,c+12*b>>2);U.uniform3fv(Z(a),d)}},Jb:(a,b,c)=>{if(2<=Y.version)b&&U.uniform3iv(Z(a),t,c>>2,3*b);else{if(96>=b){b*=3;for(var d=pd[b],e=0;e<b;e+=3)d[e]=t[c+4*e>>2],d[e+1]=t[c+(4*e+4)>>2],d[e+2]=t[c+(4*e+8)>>2]}else d=t.subarray(c>>2,c+12*b>>2);U.uniform3iv(Z(a),d)}},Mb:(a,b,c)=>{if(2<=Y.version)b&&U.uniform4fv(Z(a),v,c>>2,4*b);else{if(72>=b){var d=od[4*b],e=v;c>>=2;b*=4;for(var f=0;f<b;f+=4){var g=c+f;d[f]=e[g];d[f+1]=e[g+1];d[f+2]=e[g+2];
d[f+3]=e[g+3]}}else d=v.subarray(c>>2,c+16*b>>2);U.uniform4fv(Z(a),d)}},Ib:(a,b,c)=>{if(2<=Y.version)b&&U.uniform4iv(Z(a),t,c>>2,4*b);else{if(72>=b){b*=4;for(var d=pd[b],e=0;e<b;e+=4)d[e]=t[c+4*e>>2],d[e+1]=t[c+(4*e+4)>>2],d[e+2]=t[c+(4*e+8)>>2],d[e+3]=t[c+(4*e+12)>>2]}else d=t.subarray(c>>2,c+16*b>>2);U.uniform4iv(Z(a),d)}},Hb:(a,b,c,d)=>{if(2<=Y.version)b&&U.uniformMatrix4fv(Z(a),!!c,v,d>>2,16*b);else{if(18>=b){var e=od[16*b],f=v;d>>=2;b*=16;for(var g=0;g<b;g+=16){var k=d+g;e[g]=f[k];e[g+1]=f[k+
1];e[g+2]=f[k+2];e[g+3]=f[k+3];e[g+4]=f[k+4];e[g+5]=f[k+5];e[g+6]=f[k+6];e[g+7]=f[k+7];e[g+8]=f[k+8];e[g+9]=f[k+9];e[g+10]=f[k+10];e[g+11]=f[k+11];e[g+12]=f[k+12];e[g+13]=f[k+13];e[g+14]=f[k+14];e[g+15]=f[k+15]}}else e=v.subarray(d>>2,d+64*b>>2);U.uniformMatrix4fv(Z(a),!!c,e)}},j:a=>{a=V[a];U.useProgram(a);U.Kd=a},Rb:(a,b)=>{U.vertexAttribDivisor(a,b)},Sb:(a,b,c,d,e)=>{U.vertexAttribIPointer(a,b,c,d,e)},Tb:(a,b,c,d,e,f)=>{U.vertexAttribPointer(a,b,c,!!d,e,f)},y:(a,b,c,d)=>U.viewport(a,b,c,d),gb:Vb,
nb:function(a,b){try{return Pa(p.subarray(a,a+b)),0}catch(c){if("undefined"==typeof M||"ErrnoError"!==c.name)throw c;return c.tc}},db:function(){h.Ad=a=>{0!=Bd()&&(a.preventDefault(),a.returnValue=" ")};window.addEventListener("beforeunload",h.Ad)},cb:function(){h.Fd=a=>{const b=a.clipboardData.getData("text");vd(()=>{const c=rd(b);Ad(c)})};window.addEventListener("paste",h.Fd)},bb:function(){h.Ge=[];h.Bd=b=>{b.stopPropagation();b.preventDefault()};h.Cd=b=>{b.stopPropagation();b.preventDefault()};
h.Dd=b=>{b.stopPropagation();b.preventDefault()};h.Ed=b=>{b.stopPropagation();b.preventDefault();const c=b.dataTransfer.files;h.He=c;Cd(c.length);for(let e=0;e<c.length;e++)vd(()=>{const f=rd(c[e].name);Dd(e,f)});let d=0;b.shiftKey&&(d|=1);b.ctrlKey&&(d|=2);b.altKey&&(d|=4);b.metaKey&&(d|=8);Ed(b.clientX,b.clientY,d)};const a=h.Fc;a.addEventListener("dragenter",h.Bd,!1);a.addEventListener("dragleave",h.Cd,!1);a.addEventListener("dragover",h.Dd,!1);a.addEventListener("drop",h.Ed,!1)},Ya:function(){const a=
document.getElementById("sokol-app-favicon");a&&document.head.removeChild(a)},Zb:function(a,b){0!==b&&(document.title=O(b));a=O(a);void 0!==h.canvas&&("object"===typeof h.canvas?tc[a]=h.canvas:console.warn("sokol_app.h: Module['canvas'] is set but is not an object"));h.Fc=P(a);h.Fc||console.warn("sokol_app.h: can't find html5_canvas_selector ",a);h.Fc.requestPointerLock||console.warn("sokol_app.h: target doesn't support requestPointerLock: ",a)},Ua:function(){window.removeEventListener("beforeunload",
h.Ad)},Ta:function(){window.removeEventListener("paste",h.Fd)},Sa:function(){const a=h.Fc;a.removeEventListener("dragenter",h.Bd);a.removeEventListener("dragleave",h.Cd);a.removeEventListener("dragover",h.Dd);a.removeEventListener("drop",h.Ed)},s:function(){h.Fc&&h.Fc.requestPointerLock&&h.Fc.requestPointerLock()},_a:function(a,b){if(h.Fc){if(0===b)a="none";else switch(a){case 0:a="auto";break;case 1:a="default";break;case 2:a="text";break;case 3:a="crosshair";break;case 4:a="pointer";break;case 5:a=
"ew-resize";break;case 6:a="ns-resize";break;case 7:a="nwse-resize";break;case 8:a="nesw-resize";break;case 9:a="all-scroll";break;case 10:a="not-allowed";break;default:a="auto"}h.Fc.style.cursor=a}},Xa:function(a,b,c){const d=document.createElement("canvas");d.width=a;d.height=b;const e=d.getContext("2d"),f=e.createImageData(a,b);f.data.set(p.subarray(c,c+a*b*4));e.putImageData(f,0,0);a=document.createElement("link");a.id="sokol-app-favicon";a.rel="shortcut icon";a.href=d.toDataURL();document.head.appendChild(a)},
Za:function(a){a=O(a);const b=document.createElement("textarea");b.setAttribute("autocomplete","off");b.setAttribute("autocorrect","off");b.setAttribute("autocapitalize","off");b.setAttribute("spellcheck","false");b.style.left="-100px";b.style.top="-100px";b.style.height=1;b.style.width=1;b.value=a;document.body.appendChild(b);b.select();document.execCommand("copy");document.body.removeChild(b)},ga:function(){return navigator.userAgent.includes("Macintosh")?1:0},fa:function(a,b){b=O(b);switch(a){case 0:console.error(b);
break;case 1:console.error(b);break;case 2:console.warn(b);break;default:console.info(b)}}},Hd;
(async function(){function a(c){Hd=c.exports;ra=Hd.$b;ua();Q=Hd.nc;c=Hd;h._main=zd=c.bc;h.__sapp_emsc_onpaste=Ad=c.cc;h.__sapp_html5_get_ask_leave_site=Bd=c.dc;h.__sapp_emsc_begin_drop=Cd=c.ec;h.__sapp_emsc_drop=Dd=c.fc;h.__sapp_emsc_end_drop=Ed=c.gc;h.__sapp_emsc_invoke_fetch_cb=c.hc;Fd=c.ic;yc=c.jc;ud=c.kc;qd=c.lc;td=c.mc;ya("wasm-instantiate");return Hd}xa("wasm-instantiate");var b={a:Gd};if(h.instantiateWasm)return new Promise(c=>{h.instantiateWasm(b,(d,e)=>{c(a(d,e))})});Aa??=h.locateFile?h.locateFile("Clave.wasm",
ja):ja+"Clave.wasm";return a((await Da(b)).instance)})();function Id(a=[]){var b=zd;a.unshift(fa);var c=a.length,d=qd(4*(c+1)),e=d;a.forEach(g=>{u[e>>2]=rd(g);e+=4});u[e>>2]=0;try{var f=b(c,d);Wb(f)}catch(g){Ub(g)}}
function Jd(a=da){function b(){h.calledRun=!0;if(!pa){if(!h.noFSInit&&!ob){var c,d;ob=!0;c??=h.stdin;d??=h.stdout;e??=h.stderr;c?L("/dev","stdin",c):Gb("/dev/tty","/dev/stdin");d?L("/dev","stdout",null,d):Gb("/dev/tty","/dev/stdout");e?L("/dev","stderr",null,e):Gb("/dev/tty1","/dev/stderr");Jb("/dev/stdin",0);Jb("/dev/stdout",1);Jb("/dev/stderr",1)}Hd.ac();pb=!1;h.onRuntimeInitialized?.();h.noInitialRun||Id(a);if(h.postRun)for("function"==typeof h.postRun&&(h.postRun=[h.postRun]);h.postRun.length;){var e=
h.postRun.shift();Ga.push(e)}Fa(Ga)}}if(0<va)wa=Jd;else{if(h.preRun)for("function"==typeof h.preRun&&(h.preRun=[h.preRun]);h.preRun.length;)Ia();Fa(Ha);0<va?wa=Jd:h.setStatus?(h.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>h.setStatus(""),1);b()},1)):b()}}if(h.preInit)for("function"==typeof h.preInit&&(h.preInit=[h.preInit]);0<h.preInit.length;)h.preInit.shift()();Jd();
