// Little Wick service worker: offline launch from the home screen.
// GENERATED by tools/build-pages.mjs from tools/lib/sw-template.js (VERSION and PRECACHE are filled in).
//
// - Network first for navigations and same-origin GETs, revalidating past the HTTP cache (GitHub Pages
//   sends max-age=600), so an online launch always gets the deployed game. The cache answers only when
//   the network fails, or gives no response headers within TIMEOUT ms (dead or "lie-fi" connections).
// - Navigations fall back to the cached shell whatever the query (?newgame, ?area=...).
// - Install precaches the shell, manifest and icons, checked against the build's SHA-256 of each file
//   (a mismatch, e.g. a CDN still serving the old build, refetches past every cache with ?v=<sha>).
// - The cache is named after a hash of the whole build; activate deletes older littlewick-* caches.
// - Never touches cross-origin or non-GET requests.

const VERSION = "2539a890c3a0";
const PREFIX = 'littlewick-';
const CACHE = PREFIX + VERSION;
/** [path relative to the scope, sha256 hex] */
const PRECACHE = [["./","d1c63dd58a28f16179eaf762e111f6d7c695e3472c9fbd32951310458867f608"],["manifest.webmanifest","454eadad84c2241cc7f61d70e940f6679ff85dd21c64fd6af2e97c5137ec17dc"],["icons/apple-touch-icon.png","379177bf063720761fc409c20c8b29c4ee753fd48334d4639d7b17e2accf80e6"],["icons/icon-192.png","675ed8ba187bfb0128961db9d4a46e9eeb89246882b906315230204f1d85c28d"],["icons/icon-512.png","ceac9c67eb5c4ae2d7c6470e0a0adb763e05fe6e1f3aed4f6a3dba95c6d168bf"],["icons/maskable-512.png","44c0af15b01d5492c2bc3dd1d0f4966c53c6a3efc2066d18b010350955154cdb"],["icons/favicon-32.png","d328ba6dfb408584d83b3a3bf69bb1b5fd6ae69ac2997dfe16d115c65df97cb6"],["icons/favicon-16.png","fd5042dd6109a64cc1c531ed5cec7a621fa25be08c86f11bf815e51fbd8d7741"]];
const TIMEOUT = 4000;

const scope = self.registration.scope;
const SHELL = scope; // './' is index.html
const keys = new Set(PRECACHE.map(([p]) => new URL(p, scope).href));

async function sha256(buf) {
  const d = new Uint8Array(await crypto.subtle.digest('SHA-256', buf));
  return Array.from(d, (b) => b.toString(16).padStart(2, '0')).join('');
}

async function fetchVerified(path, sha) {
  const url = new URL(path, scope).href;
  for (const [u, cache] of [[url, 'no-cache'], [url + '?v=' + sha.slice(0, 16), 'reload']]) {
    const res = await fetch(u, { cache, credentials: 'same-origin' });
    if (!res.ok) continue;
    const body = await res.arrayBuffer();
    if ((await sha256(body)) !== sha) continue;
    const headers = new Headers();
    for (const h of ['content-type', 'last-modified', 'etag']) if (res.headers.has(h)) headers.set(h, res.headers.get(h));
    return [url, new Response(body, { status: 200, headers })];
  }
  throw new Error('precache: ' + path + ' does not match this build');
}

self.addEventListener('install', (event) => {
  event.waitUntil((async () => {
    const entries = await Promise.all(PRECACHE.map(([p, sha]) => fetchVerified(p, sha)));
    const cache = await caches.open(CACHE);
    await Promise.all(entries.map(([url, res]) => cache.put(url, res)));
    await self.skipWaiting();
  })());
});

self.addEventListener('activate', (event) => {
  event.waitUntil((async () => {
    for (const k of await caches.keys()) if (k.startsWith(PREFIX) && k !== CACHE) await caches.delete(k);
    await self.clients.claim();
  })());
});

/** A navigation must not be answered with a redirected response: copy it into a fresh one. */
function clean(res) {
  if (!res.redirected) return res;
  return new Response(res.body, { status: res.status, statusText: res.statusText, headers: res.headers });
}

self.addEventListener('fetch', (event) => {
  const req = event.request;
  if (req.method !== 'GET') return;
  const url = new URL(req.url);
  if (url.origin !== self.location.origin || !url.href.startsWith(scope)) return;
  if (url.href === new URL('sw.js', scope).href) return;
  const nav = req.mode === 'navigate';
  // the cache entry this request maps to: the shell for the scope root / index.html whatever the query
  const bare = url.origin + url.pathname;
  const key = bare === SHELL || bare === SHELL + 'index.html' ? SHELL : keys.has(bare) && !url.search ? bare : null;

  let put = Promise.resolve();
  const net = fetch(nav ? url.href : req, nav ? { cache: 'no-cache', credentials: 'same-origin' } : { cache: 'no-cache' })
    .then((res) => {
      // keep the cached copy in step with what the network serves
      if (key && res.ok && res.status === 200 && res.type === 'basic' && !res.redirected) {
        const copy = res.clone();
        put = caches.open(CACHE).then((c) => c.put(key, copy)).catch(() => {});
      }
      return res;
    });
  event.waitUntil(net.then(() => put, () => {}));

  event.respondWith((async () => {
    const cached = () => caches.open(CACHE).then((c) =>
      nav ? c.match(SHELL) : c.match(req)).then((r) => r || caches.match(req, { ignoreSearch: nav }));
    let timer;
    const late = new Promise((resolve) => { timer = setTimeout(resolve, TIMEOUT, 'timeout'); });
    try {
      const res = await Promise.race([net, late]);
      if (res !== 'timeout') {
        // a server error on launch: the cached game beats an error page
        if (nav && res.status >= 500) { const c = await cached(); if (c) return c; }
        return clean(res);
      }
      const c = await cached();
      if (c) return c;
      return clean(await net);
    } catch (err) {
      const c = await cached();
      if (c) return c;
      throw err;
    } finally {
      clearTimeout(timer);
    }
  })());
});
